const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs');
const server = require('../server.cjs');
(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1024, height: 768 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('response', response => { if (response.status() >= 400) errors.push(response.url()); });
    await page.addInitScript(() => {
      window.media = []; window.gains = []; window.decoded = 0; window.started = 0;
      const NativeAudio = window.Audio;
      window.Audio = function (...args) { const audio = new NativeAudio(...args); media.push(audio); return audio; };
      const createGain = AudioContext.prototype.createGain;
      AudioContext.prototype.createGain = function () { const gain = createGain.call(this); gains.push(gain); return gain; };
      const decode = AudioContext.prototype.decodeAudioData;
      AudioContext.prototype.decodeAudioData = async function (...args) { const result = await decode.apply(this, args); decoded++; return result; };
      const start = AudioBufferSourceNode.prototype.start;
      AudioBufferSourceNode.prototype.start = function (...args) { started++; return start.apply(this, args); };
    });
    await page.goto(`http://127.0.0.1:${server.address().port}`);
    await page.waitForFunction(() => !document.getElementById('start').disabled);
    assert.equal(await page.evaluate(() => decoded), 47, 'All 45 recordings and two effects decode');
    await page.evaluate(() => {
      window.voices = []; window.effects = [];
      const voice = gameSounds.voice, play = gameSounds.play;
      gameSounds.voice = name => { voices.push(name); return voice(name); };
      gameSounds.play = name => { effects.push({ name, flight: !!document.querySelector('.flying-scale') }); play(name); };
    });
    await page.locator('input[value="both"]').check();
    await page.locator('#start').click();
    await page.waitForFunction(() => voices.length === 2);
    const target = Number(await page.locator('#target').textContent());
    assert.deepEqual(await page.evaluate(() => voices.slice(0, 2)), ['uitleg', `${String(target).padStart(2, '0')}geven`]);
    assert.ok(await page.evaluate(() => started >= 2), 'Recordings really play through Web Audio');
    assert.ok(await page.evaluate(() => media.find(a => a.src.endsWith('/achtergrondmuziek.mp3')).loop));
    await page.waitForFunction(() => !media.find(a => a.src.endsWith('/achtergrondmuziek.mp3')).paused);
    assert.ok(await page.evaluate(() => gains[0].gain.value < .11), 'Music is quiet, including during speech');
    await page.locator('#music').click();
    assert.equal(await page.locator('#music').getAttribute('aria-pressed'), 'false');
    assert.ok(await page.evaluate(() => media.find(a => a.src.endsWith('/achtergrondmuziek.mp3')).paused));
    await page.locator('#thought').click();
    assert.equal(await page.evaluate(() => voices.at(-1)), String(target).padStart(2, '0'));
    await page.locator('#shell').click();
    await page.waitForFunction(() => !document.querySelector('.swimming'));
    await page.locator('.fish').click();
    assert.equal(await page.evaluate(() => effects.filter(e => e.name === 'plop').length), 2, 'Add and remove both plop');
    await page.waitForFunction(() => !document.getElementById('rainbow').disabled);
    const wrong = target === 1 ? 2 : 1;
    await page.evaluate(n => { for (let i = 0; i < n; i++) document.getElementById('shell').click(); }, wrong);
    await page.locator('#rainbow').click();
    await page.waitForFunction(() => document.querySelector('.disappointed'));
    assert.equal(await page.locator('.has-scale, .flying-scale').count(), 0);
    fs.mkdirSync('tests/artifacts', { recursive: true });
    await page.waitForTimeout(230);
    await page.screenshot({ path: 'tests/artifacts/disappointed-fish.png' });
    await page.waitForFunction(() => document.querySelector('.disappointed.departing'));
    assert.equal(await page.locator('.disappointed').first().evaluate(el => el.getAnimations().find(a => a.effect.getKeyframes()[0].top).effect.getTiming().duration), 1250);
    await page.waitForFunction(() => !document.getElementById('rainbow').disabled);
    assert.equal(await page.locator('#target').textContent(), String(target));
    assert.equal(await page.evaluate(() => effects.filter(e => e.name === 'glitter').length), 0);
    assert.ok(await page.evaluate(key => voices.includes(key), wrong < target ? 'nognietgenoegvisjesprobeernogeens' : 'teveelvisjesprobeerhetnogeens'));
    await page.evaluate(n => { for (let i = 0; i < n; i++) document.getElementById('shell').click(); }, target);
    await page.locator('#rainbow').click();
    await page.waitForFunction(() => document.querySelector('.flying-scale'));
    assert.deepEqual(await page.evaluate(() => effects.find(e => e.name === 'glitter')), { name: 'glitter', flight: true });
    await page.waitForFunction(() => document.getElementById('shell').classList.contains('open'), null, { timeout: 20000 });
    assert.ok(await page.evaluate(() => voices.includes('goed geteld')));
    await page.screenshot({ path: 'tests/artifacts/open-shell-plant.png' });
    await page.locator('#music').click();
    await page.locator('#home').click();
    assert.ok(await page.evaluate(() => media.find(a => a.src.endsWith('/achtergrondmuziek.mp3')).paused));
    await page.locator('#start').click();
    await page.locator('#music').click();
    await page.reload();
    await page.waitForFunction(() => !document.getElementById('start').disabled);
    await page.locator('#start').click();
    assert.equal(await page.locator('#music').getAttribute('aria-pressed'), 'false', 'Music preference persists');
    assert.equal((await page.locator('#play').innerText()).trim(), await page.locator('#target').textContent());
    assert.deepEqual(errors, []);
    await page.close();
    const local = await browser.newPage();
    await local.goto(pathToFileURL(path.resolve(__dirname, '../index.html')).href);
    await local.waitForFunction(() => !document.getElementById('start').disabled);
    await local.evaluate(() => {
      window.plays = [];
      const play = HTMLMediaElement.prototype.play;
      HTMLMediaElement.prototype.play = function (...args) { if (!this.muted) plays.push(this.src); return play.apply(this, args); };
    });
    await local.locator('#start').click();
    await local.locator('#thought').click();
    assert.ok(await local.evaluate(() => plays.some(src => /voice\/\d\d.mp3$/.test(src))));
    await local.locator('#shell').click();
    assert.ok(await local.evaluate(() => plays.some(src => src.endsWith('/plop.mp3'))));
    await local.close();
    console.log('PASS: recordings decode/play, intro, assignment, number, error/reward, quiet looping music/toggle/persistence, plop add/remove, wrong fish without scales and slow descent, correct glitter, Home and file fallback.');
  } finally { await browser.close(); server.close(); }
})().catch(error => { console.error(error); server.close(); process.exitCode = 1; });
